[2023-01-16T01:55:49.182+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: producer.update_dataset scheduled__2023-01-13T00:00:00+00:00 [queued]>
[2023-01-16T01:55:49.314+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: producer.update_dataset scheduled__2023-01-13T00:00:00+00:00 [queued]>
[2023-01-16T01:55:49.325+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-16T01:55:49.332+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-16T01:55:49.334+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-16T01:55:49.625+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): update_dataset> on 2023-01-13 00:00:00+00:00
[2023-01-16T01:55:49.991+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'producer', 'update_dataset', 'scheduled__2023-01-13T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/producer.py', '--cfg-path', '/tmp/tmplaaem6kw']
[2023-01-16T01:55:50.019+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask update_dataset
[2023-01-16T01:55:49.963+0000] {standard_task_runner.py:55} INFO - Started process 8311 to run task
[2023-01-16T01:55:51.757+0000] {task_command.py:376} INFO - Running <TaskInstance: producer.update_dataset scheduled__2023-01-13T00:00:00+00:00 [running]> on host e4c135bf00be
[2023-01-16T01:55:52.858+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: producer.update_dataset scheduled__2023-01-13T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-01-16T01:55:52.898+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: producer.update_dataset scheduled__2023-01-13T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-01-16T01:55:52.923+0000] {local_task_job.py:103} INFO - Task is not able to be run
[2023-01-16T01:55:53.361+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=producer
AIRFLOW_CTX_TASK_ID=update_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-13T00:00:00+00:00
[2023-01-16T01:55:53.457+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-16T01:55:53.525+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/baseoperator.py:1390: RemovedInAirflow3Warning: Passing 'execution_date' to 'TaskInstance.xcom_push()' is deprecated.
  context['ti'].xcom_push(key=key, value=value, execution_date=execution_date)

[2023-01-16T01:55:54.111+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=producer, task_id=update_dataset, execution_date=20230113T000000, start_date=20230116T015549, end_date=20230116T015554
[2023-01-16T01:55:55.147+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-16T01:55:55.913+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
