[2022-11-27T10:01:39.051+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-11-27T10:01:33.178732+00:00 [queued]>
[2022-11-27T10:01:39.064+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-11-27T10:01:33.178732+00:00 [queued]>
[2022-11-27T10:01:39.066+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T10:01:39.068+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-27T10:01:39.069+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T10:01:39.087+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-11-27 10:01:33.178732+00:00
[2022-11-27T10:01:39.104+0000] {standard_task_runner.py:55} INFO - Started process 5423 to run task
[2022-11-27T10:01:39.111+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-11-27T10:01:33.178732+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpgypcnfa8']
[2022-11-27T10:01:39.116+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask is_api_available
[2022-11-27T10:01:39.204+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-11-27T10:01:33.178732+00:00 [running]> on host c7f7231a8603
[2022-11-27T10:01:39.270+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-11-27T10:01:33.178732+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-27T10:01:33.178732+00:00
[2022-11-27T10:01:39.273+0000] {http.py:120} INFO - Poking: api/
[2022-11-27T10:01:39.287+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2022-11-27T10:01:39.295+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-11-27T10:01:39.739+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2022-11-27T10:01:39.763+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20221127T100133, start_date=20221127T100139, end_date=20221127T100139
[2022-11-27T10:01:39.824+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-27T10:01:39.868+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
