[2023-01-16T03:55:25.964+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-16T03:55:23.350693+00:00 [queued]>
[2023-01-16T03:55:25.978+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-16T03:55:23.350693+00:00 [queued]>
[2023-01-16T03:55:25.979+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-16T03:55:25.981+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-16T03:55:25.982+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-16T03:55:25.999+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-16 03:55:23.350693+00:00
[2023-01-16T03:55:26.004+0000] {standard_task_runner.py:55} INFO - Started process 4251 to run task
[2023-01-16T03:55:26.008+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-01-16T03:55:23.350693+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpimxd1bx4']
[2023-01-16T03:55:26.011+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask is_api_available
[2023-01-16T03:55:26.075+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-01-16T03:55:23.350693+00:00 [running]> on host c4d6e9176664
[2023-01-16T03:55:26.144+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-16T03:55:23.350693+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-16T03:55:23.350693+00:00
[2023-01-16T03:55:26.146+0000] {http.py:120} INFO - Poking: api/
[2023-01-16T03:55:26.158+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-01-16T03:55:26.161+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-16T03:55:26.704+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-01-16T03:55:26.714+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230116T035523, start_date=20230116T035525, end_date=20230116T035526
[2023-01-16T03:55:26.745+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-16T03:55:26.859+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
